name = "drakeshot"
default_targets = ["macos", "appimage", "win64", "lovejs"]
build_directory = "makelove-build"

love_files = [
    "::git-ls-tree::",
    "-*/.*",
    "-*/dist*",
    "*/libs*",
]

[lovejs]
title = "Drakeshot"
memory = "200000000"  # starting memory of the webpage (default is 20 MB)

[macos]
# optionally, you can include a mac-specific icon, if not mac will use the same icon as other targets
#icon_file = "macIcon.png"  # or macIcon.icns

[macos.app_metadata]
CFBundleName = "Drakeshot"
CFBundleIdentifier = "dev.micahturner.drakeshot"
NSHumanReadableCopyright = "Copyright © 2024 Micah Turner"
CFBundleShortVersionString = "0.0.1"

[windows.exe_metadata]
FileDescription = "{name} - {version}" # "LÖVE {löve version}"
FileVersion = "{version}" # "{löve version}"
CompanyName = "Micah Turner" # "LÖVE World Domination Inc."
LegalCopyright = "Copyright © 2024 Micah Turner"
ProductName = "{name}" # "LÖVE"
ProductVersion = "{version}"
OriginalFilename = "drakeshot.exe" # "love.exe"
